/**
 * Generates the compiler's view of its own two version numbers.
 *
 * Both are facts that already exist somewhere else, so neither is typed into
 * source. A number typed twice is a number that will disagree on the day
 * somebody edits one copy, and these two disagreeing is expensive in a specific
 * way for each of them.
 *
 *   VERSION                 from package.json.
 *   COMPILED_FORMAT_VERSION from spec/compiled-program.md.
 *
 * **Why the package version is worth exporting at all.** An engine that reports
 * a different version than the registry says it is makes every bug report
 * unanswerable: a trader says the study is wrong, and nobody can establish which
 * build produced the number. So the release refuses to publish unless the tag,
 * the manifest and the built artifact all agree, and this is what lets the built
 * artifact have an opinion.
 *
 * **Why the format version is a different number, moving at a different speed.**
 * Somebody implementing the compiled program in Java or Go targets the FORMAT,
 * not this package. The package can reach 2.0 for an API change while the format
 * stays at 1 and their engine keeps working. What must never happen is the
 * format version drifting between the document they implemented from and the
 * compiler that emits it: then the specification describes something we no
 * longer produce, and the first they hear of it is a program their engine
 * refuses.
 *
 * Like the error catalogue, the output is not kept in version control. A checked
 * in copy is the second copy this rule exists to prevent.
 *
 * Run: node scripts/generate-version.mjs
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

const spec = readFileSync(join(root, 'spec', 'compiled-program.md'), 'utf8');
const stated = spec.match(/compiled format version\s+([0-9]+(?:\.[0-9]+)*)/i);
if (!stated) {
  console.error(
    'spec/compiled-program.md does not state a compiled format version.\n' +
      'The compiler cannot report a number the specification does not document, ' +
      'because that number is what a third party implements against.',
  );
  process.exit(1);
}

const out = join(root, 'src', 'core', 'version');
mkdirSync(out, { recursive: true });

writeFileSync(
  join(out, 'version.generated.ts'),
  `// Generated by scripts/generate-version.mjs. Do not edit.
//
// VERSION comes from package.json and COMPILED_FORMAT_VERSION from
// spec/compiled-program.md, so neither can drift from the thing it names.

/** This build's package version. The release refuses to publish unless the tag, the manifest and this agree. */
export const VERSION = ${JSON.stringify(pkg.version)};

/**
 * The compiled program format this compiler emits.
 *
 * Deliberately not the package version. An engine written by somebody else
 * targets this number, and it moves only when the format does.
 */
export const COMPILED_FORMAT_VERSION = ${JSON.stringify(stated[1])};
`,
  'utf8',
);

writeFileSync(
  join(out, 'index.ts'),
  `export { COMPILED_FORMAT_VERSION, VERSION } from './version.generated.js';
`,
  'utf8',
);

console.log(
  `Version generated: package ${pkg.version}, compiled format ${stated[1]} from the specification.`,
);
